version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ll-dev
      POSTGRES_PASSWORD: ll-dev
      POSTGRES_DB: living_lens
    volumes:
      - ./dev/dev_3.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8383:5432"

  fastapi:
    build:
      context: .
      dockerfile: dev/dev.Dockerfile
    environment:
      PG_USER: ll-dev
      PG_PASSWORD: ll-dev
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: living_lens
    ports:
      - "8080:80"
    depends_on:
      - db
