"""Initial migration

Revision ID: 64c0a34bccf8
Revises: 
Create Date: 2024-03-31 15:28:44.599077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c0a34bccf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('country_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id_fk'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(length=100), nullable=True),
    sa.Column('category_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id_fk'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id_fk', sa.Integer(), nullable=True),
    sa.Column('subcategory_id_fk', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id_fk'], ['city.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id_fk'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('subcategory')
    op.drop_table('city')
    op.drop_table('country')
    op.drop_table('category')
    # ### end Alembic commands ###
